force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Phone Screen</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Schedule Interview</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DashboardController.cls
public with sharing class DashboardController {

    @AuraEnabled(cacheable=true)
    public static Map<String, Integer> getApplicationStats() {
        
        Map<String, Integer> stats = new Map<String, Integer>();

        stats.put('Total', [SELECT COUNT() FROM Job_Application__c]);
        stats.put('Applied', [SELECT COUNT() FROM Job_Application__c WHERE Status__c = 'Applied']);
        stats.put('Rejected', [SELECT COUNT() FROM Job_Application__c WHERE Status__c = 'Rejected']);
        stats.put('Interview', [SELECT COUNT() FROM Job_Application__c WHERE Status__c = 'Schedule Interview']);

        return stats;
    }
}